Repository helloaashu/Hamro-University, pull requests merged in 2025-10, with the labels that each got.

#65 dsap note
  Pokhara University/8thsem/DSAP.pdf
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#68 depreciation eco
  Pokhara University/8thsem/8. Depreciation.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#69 Add TU info
  Tribhuvan University /Info.txt
Labels: hacktoberfest, hacktoberfest-accepted

#71 Add nepali poems (js code)
  Tribhuvan University /poems/poem1.js
  Tribhuvan University /poems/poem2.js
Labels: hacktoberfest, hacktoberfest-accepted

#72 Add PDFs related to TU
  Tribhuvan University /pdfs/syllcompengg.pdf
  Tribhuvan University /pdfs/tu-pocket-calendar-2082.pdf
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#73 Add Course Catalog website code
  Tribhuvan University /Code/course.html
  Tribhuvan University /pdfs/computerprogramming-course-structure.pdf
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#74 Add TU Complete Overview Website
  Tribhuvan University /index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
